spring:
  application:
    name: pocapi

  datasource:
    url: jdbc:postgresql://localhost:5432/pocdb
    username: pocuser
    password: pocpass

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
